# Generated by Django 4.0.3 on 2022-04-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recognizer',
            field=models.CharField(blank=True, default=None, max_length=4096, null=True, unique=True, verbose_name='recognizer'),
        ),
    ]
